// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor
package generator

// NewConstructorGenerator insitanciate Constructor
func NewConstructorGenerator(
	fileWriter FileWriter,
) Constructor {
	return Constructor{
		FileWriter: fileWriter,
	}
}
