// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor
package generator

// NewConstructorImplGenerator insitanciate ConstructorImpl
func NewConstructorImplGenerator(
	sourceCodeReader reader.Code,
	templateReader reader.Template,
	yamlReader reader.Yaml,
) ConstructorImpl {
	return ConstructorImpl{
		SourceCodeReader: sourceCodeReader,
		TemplateReader:   templateReader,
		YamlReader:       yamlReader,
	}
}

// NewgenerateComponentGenerator insitanciate generateComponent
func NewgenerateComponentGenerator(
	destinationPath raw.Path,
	_package string,
) generateComponent {
	return generateComponent{
		DestinationPath: destinationPath,
		Package:         _package,
	}
}

// NewTemplateGenerator insitanciate Template
func NewTemplateGenerator() Template {
	return Template{}
}

// NewYamlGenerator insitanciate Yaml
func NewYamlGenerator() Yaml {
	return Yaml{}
}
