// Code generated by MockGen. DO NOT EDIT.
// Source: generator/template_reader.go

// Package generator is a generated GoMock package.
package generator

import (
	structure "github.com/constructor/structure"
	gomock "github.com/golang/mock/gomock"
	template "html/template"
	reflect "reflect"
)

// TemplateReaderMock is a mock of TemplateReader interface
type TemplateReaderMock struct {
	ctrl     *gomock.Controller
	recorder *TemplateReaderMockMockRecorder
}

// TemplateReaderMockMockRecorder is the mock recorder for TemplateReaderMock
type TemplateReaderMockMockRecorder struct {
	mock *TemplateReaderMock
}

// NewTemplateReaderMock creates a new mock instance
func NewTemplateReaderMock(ctrl *gomock.Controller) *TemplateReaderMock {
	mock := &TemplateReaderMock{ctrl: ctrl}
	mock.recorder = &TemplateReaderMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *TemplateReaderMock) EXPECT() *TemplateReaderMockMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *TemplateReaderMock) Read(filePath structure.Path) *template.Template {
	ret := m.ctrl.Call(m, "Read", filePath)
	ret0, _ := ret[0].(*template.Template)
	return ret0
}

// Read indicates an expected call of Read
func (mr *TemplateReaderMockMockRecorder) Read(filePath interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*TemplateReaderMock)(nil).Read), filePath)
}
