package generator

import (
	"fmt"

	"github.com/bannzai/constructor/file"
	"github.com/bannzai/constructor/structure"
)

type Template struct{}

const defaultTemplate = `// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor

{{- $dot := . }}
package {{.Package}}

{{range $i, $struct := .Structs -}}
{{- $suffix := upperCamelCase $dot.Package -}}
{{- $structureName := .Name -}}
// New{{$structureName}}{{$suffix}} insitanciate {{.Name}}
func New{{$structureName}}{{$suffix}}(
	{{range $i, $field := .Fields -}}
		{{parameterCase $field.Name}} {{$field.Type}},
	{{end -}}
) {{$structureName}} {
	return {{$structureName}}{
		{{range $i, $field := .Fields -}}
			{{$field.Name}}: {{argumentCase $field.Name}},
		{{end -}}
	}
}
{{end}}
`

func (impl Template) Setup() {
	if file.FileExists(structure.TemplateFileName) {
		fmt.Println(structure.TemplateFileName + " is already exists. Not generate " + structure.TemplateFileName)
		return
	}
	file.WriteFile(structure.TemplateFileName, defaultTemplate)
}
