// Code generated by MockGen. DO NOT EDIT.
// Source: generator/yaml_reader.go

// Package generator is a generated GoMock package.
package generator

import (
	structure "github.com/bannzai/constructor/structure"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// YamlReaderMock is a mock of YamlReader interface
type YamlReaderMock struct {
	ctrl     *gomock.Controller
	recorder *YamlReaderMockMockRecorder
}

// YamlReaderMockMockRecorder is the mock recorder for YamlReaderMock
type YamlReaderMockMockRecorder struct {
	mock *YamlReaderMock
}

// NewYamlReaderMock creates a new mock instance
func NewYamlReaderMock(ctrl *gomock.Controller) *YamlReaderMock {
	mock := &YamlReaderMock{ctrl: ctrl}
	mock.recorder = &YamlReaderMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *YamlReaderMock) EXPECT() *YamlReaderMockMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *YamlReaderMock) Read() structure.Yaml {
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(structure.Yaml)
	return ret0
}

// Read indicates an expected call of Read
func (mr *YamlReaderMockMockRecorder) Read() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*YamlReaderMock)(nil).Read))
}
