// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor

{{- $dot := . -}}
package {{.Package}}

{{range $i, $field := .Structs -}}
{{- $suffix := upperCamelCase $dot.Package -}}
{{- $structureName := $dot.Name -}}
// New{{$structureName}}{{$suffix}} insitanciate {{$dot.Name}}
func New{{$structureName}}{{$suffix}}(
	{{range $i, $field := $dot.Fields -}}
		{{parameterCase $field}} {{$field}},
	{{end}}
) {{$structureName}} {
	return {{$structureName}}{{$suffix}}{
		{{range $i, $field := $dot.Fields -}}
			{{$field}}: {{argumentCase $field}},
		{{end}}
	}
}
{{end}}
