version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/constructor
    steps:
      - checkout
      - run: make dependency
      - run: make test-verbose


workflows:
  version: 2
  test:
    jobs: 
      - test
