// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor
package raw

// NewArgumentRaw insitanciate Argument
func NewArgumentRaw(
	yamlPath Path,
) Argument {
	return Argument{
		YamlPath: yamlPath,
	}
}

// NewCodeRaw insitanciate Code
func NewCodeRaw(
	filePath Path,
) Code {
	return Code{
		FilePath: filePath,
	}
}

// NewFieldRaw insitanciate Field
func NewFieldRaw(
	name string,
	_type string,
) Field {
	return Field{
		Name: name,
		Type: _type,
	}
}

// NewStructRaw insitanciate Struct
func NewStructRaw(
	name string,
) Struct {
	return Struct{
		Name: name,
	}
}

// NewDefinitionRaw insitanciate Definition
func NewDefinitionRaw(
	destinationPath Path,
	_package string,
	sourcePath Path,
) Definition {
	return Definition{
		DestinationPath: destinationPath,
		Package:         _package,
		SourcePath:      sourcePath,
	}
}

// NewYamlRaw insitanciate Yaml
func NewYamlRaw() Yaml {
	return Yaml{}
}
