// DO NOT EDIT THIS FILE.
// File generated by constructor.
// https://github.com/bannzai/constructor
package raw

// NewArgumentRaw insitanciate Argument
func NewArgumentRaw(
	yamlPath Path,
) Argument {
	return Argument{
		YamlPath: yamlPath,
	}
}

// NewCodeRaw insitanciate Code
func NewCodeRaw(
	structs []Struct,
) Code {
	return Code{
		Structs: structs,
	}
}

// NewFieldRaw insitanciate Field
func NewFieldRaw(
	name string,
	_type string,
) Field {
	return Field{
		Name: name,
		Type: _type,
	}
}

// NewStructRaw insitanciate Struct
func NewStructRaw(
	fields []Field,
	name string,
) Struct {
	return Struct{
		Fields: fields,
		Name:   name,
	}
}

// NewDefinitionRaw insitanciate Definition
func NewDefinitionRaw(
	destinationPath Path,
	ignoredPaths []Path,
	_package string,
	sourcePath Path,
	templateFilePaths []Path,
) Definition {
	return Definition{
		DestinationPath:   destinationPath,
		IgnoredPaths:      ignoredPaths,
		Package:           _package,
		SourcePath:        sourcePath,
		TemplateFilePaths: templateFilePaths,
	}
}

// NewYamlRaw insitanciate Yaml
func NewYamlRaw(
	definitions []Definition,
) Yaml {
	return Yaml{
		Definitions: definitions,
	}
}
